const types = {
  LOGIN_REQUEST_TYPE: 'LOGIN_REQUEST_TYPE',
  LOGIN_SUCCESS_TYPE: 'LOGIN_SUCCESS_TYPE',
  LOGIN_FAILURE_TYPE: 'LOGIN_FAILURE_TYPE',
  REGISTER_REQUEST_TYPE: 'REGISTER_REQUEST_TYPE',
  REGISTER_SUCCESS_TYPE: 'REGISTER_SUCCESS_TYPE',
  REGISTER_FAILURE_TYPE: 'REGISTER_FAILURE_TYPE',
};

export default types;
